### ISSUE TITLE
Share link downloads file instead of opening in app

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio-nextcloud#4]
- When clicking a .drawio file in the files app it's opened with the drawio app correctly.
- When clicking on a share link for a shared .drawio file it only downloads the file.

NC Version is 24.0.4.1, drawio app is up-to-date.

mimetypemapping.dist.json  in config folder contains:
```
 {
    "drawio": [
        "application/x-drawio"
    ]
}
```

**Comment by selyod-ka** [comment]
exactly the same in my installation. the drawio-file does not have to be shared, though. when clicking on the link to a drawio-file from the dashboard, it get's downloaded, not opened.

**Comment by davidjgraph** [comment]
Could you maybe show us a video or screenshots please? We're not actually nextcloud users, so not very familiar with it.

**Comment by aov-arnold** [comment]
Sure!

When clicking on a .drawio file in the files app...
<img src="https://user-images.githubusercontent.com/57179682/202404748-5c6f4dd3-174c-4100-b71a-30324f74f27b.png" width="400">

...it opens correctly in the embedded editor:
<img src="https://user-images.githubusercontent.com/57179682/202404837-1a5007d5-d23c-421d-925d-2d80bc8837ba.png" width="400">

When clicking the file on the dashboard...
<img src="https://user-images.githubusercontent.com/57179682/202406071-85cc069e-1c33-4148-979b-6c0d55ff7fcf.png" width="400">

... it's downloaded instead of opened in the app:
<img src="https://user-images.githubusercontent.com/57179682/202406278-49239a97-b555-47d9-b76b-23b712bd2e32.png" width="300">

When clicking a link a new button "Open in Draw.io" appeared. That wasn't the case when I opened this issue in my opinion...

Opening it in the draw.io app directly would be still more convenient and it would be the same behaviour as for office files (NC Office). Downloading the files would be still possible within the app.
<img src="https://user-images.githubusercontent.com/57179682/202406927-39536b21-e879-4b54-b4a0-1a2f6b3103f9.png" width="200">

**Comment by matbgn** [comment]
I can only double this to the fact that it's actually impossible for an outside member who received a full sharable link to interact with draw.io 

What would be needed to overcome this?

**Comment by m-mohamedin** [comment]
@aov-arnold Can you please show me how the file is added to the dashboard?

Also, in the next version, editing shared files will be added

**Comment by aov-arnold** [comment]
@m-mohamedin Sounds good! The most recently used files appear in the recommended files widget automatically.

**Comment by m-mohamedin** [comment]
> @m-mohamedin Sounds good! The most recently used files appear in the recommended files widget automatically.

I've tried the latest version and there clicking a file takes you to the file in the file explorer without opening or downloading. I think this issue is related to the Recommendations app?

**Comment by ZID-TU-Graz** [comment]
we've updated the app to 2.1.0 (NC 25.0.2), but the issue still exists on our instance: when share via link (in our case a folder), the drawio file is only downloaded

**Comment by m-mohamedin** [comment]
> yes we selected allowing editing. We've tried now to share a file via link (instead of the whole directory [with editing rights]), then it works as expected. It does not work when sharing the whole directory, but maybe this is another issue...

Yes, folder sharing is not supported yet. Please open a new issue for that

**Comment by m-mohamedin** [comment]
@aov-arnold Is this issue resolved now?
