### ISSUE TITLE
Cannot use HTTP

### ISSUE THREAD

**Issue by exactoph** [jgraph/drawio-nextcloud#46]
When using a own draw.io instance, it is not possible to use HTTP.
When you enter a HTTP link as "Draw.io URL" and try to open a file, it just shows the loading icon and never opens the file.

Don't want to use HTTPS in this specific case due to other circumstances.

**Comment by davidjgraph** [comment]
We don't want to support non-https. Security is a key focus of the project and https is very easy since let's encrypt.

**Comment by exactoph** [comment]
The draw.io instance is not reachable through internet, so let's encrypt is no alternative as we don't have a public DNS neither. 
Well then we probably need to secure it up even when it's on the same host and does not make sense at all here ...

**Comment by davidjgraph** [comment]
OK, we'll leave it open in case someone wants to look.

**Comment by jjasoncool** [comment]
I want to use draw.io behind reverse proxy, but I can't because of https.

**Comment by m-mohamedin** [comment]
Hi,

I've tested http and the problem is from Chrome forcing redirection to https. Once that is disabled, I managed to use http site including the localhost. You can check this method to disable automatic redirection https://howchoo.com/chrome/stop-chrome-from-automatically-redirecting-https

Please try and let us know.
